[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "style", "index.html"]
ignore = ["./dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = false

[clean]
dist = "dist"
